services:
#    login.example:
#        class: LoginBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
   App\Bundle\LoginBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']