swagger: '2.0'
info:
  title: 后台接口文档
  description:
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0
host:
basePath: /
schemes:
  - http
paths:
  /api/user:
    get:
      tags:
        - userInfo
      summary: 用户管理
      parameters:
        - name: page
          in: query
          description: 页码
          type: integer
        - name: unick
          in: query
          description: 昵称
          type: string
        - name: uuid
          in: query
          description: uuid
          type: string
        - name: u_type
          in: query
          description: 账号类型
          type: string
        - name: start_time
          in: query
          description: 开始时间
          type: string
        - name: end_time
          in: query
          description: 结束时间
          type: string
        - name: type
          in: query
          description: 时间筛选类型
          type: string
      responses:
        '200':
          description: '[SUCCESS]设置成功'
          schema:
            $ref: '#/definitions/userInfoResponse'
      security:
        - api_key: []
  /api/user/delete/{id}:
    delete:
      tags:
        - userInfo
      summary: 用户管理
      parameters:
        - name: uid
          in: path
          required: true
          description: 用户id
          type: integer
      responses:
        '200':
          description: '[SUCCESS]设置成功'
          schema:
            $ref: '#/definitions/ApiResponse'
      security:
        - api_key: []
  /api/room:
    get:
      tags:
        - roomInfo
      summary: 房间信息
      parameters:
        - name: room_type
          in: query
          required: false
          description: 房间类型
          type: string
        - name: room_state
          in: query
          required: false
          description: 房间状态
          type: string
        - name: page
          in: query
          required: false
          description: 页码
          type: integer
      responses:
        '200':
          description: '[SUCCESS]设置成功'
          schema:
            $ref: '#/definitions/roomInfoResponse'
      security:
        - api_key: []
  /api/reg:
    get:
      tags:
        - Config
      summary: 注册配置
      responses:
        '200':
          description: '[SUCCESS]设置成功'
          schema:
            $ref: '#/definitions/regResponse'
      security:
        - api_key: []
  /api/reg/{id}:
    put:
      tags:
        - Config
      summary: 更新注册配置
      parameters:
        - name: id
          type: integer
          in: path
          required: true
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/EditReg'
      responses:
        '200':
          description: '[SUCCESS]设置成功'
          schema:
            $ref: '#/definitions/regResponse'
      security:
        - api_key: []
  /api/sign:
    get:
      tags:
        - Config
      summary: 签到配置
      parameters:
        - name: page
          in: query
          required: false
          description: 页码
          type: integer
      responses:
        '200':
          description: '[SUCCESS]设置成功'
          schema:
            $ref: '#/definitions/signResponse'
      security:
        - api_key: []
  /api/sign/add:
    post:
      tags:
        - Config
      summary: 添加签到配置
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/signAdd'
      responses:
        '200':
          description: '[SUCCESS]设置成功'
          schema:
            $ref: '#/definitions/ApiResponse'
      security:
        - api_key: []
  /api/sign/{id}:
    put:
      tags:
        - Config
      summary: 更新签到配置
      parameters:
        - name: id
          in: path
          required: true
          type: integer
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/signAdd'
      responses:
        '200':
          description: '[SUCCESS]设置成功'
          schema:
            $ref: '#/definitions/ApiResponse'
      security:
        - api_key: []
  /api/sign/delete/{id}:
    delete:
      tags:
        - Config
      summary: 删除签到配置
      parameters:
        - name: id
          in: path
          required: true
          description: id
          type: integer
      responses:
        '200':
          description: '[SUCCESS]设置成功'
          schema:
            $ref: '#/definitions/ApiResponse'
      security:
        - api_key: []
  /api/simplelogin:
    post:
      tags:
        - userInfo
      summary: 管理员登陆
      parameters:
        - name: data
          in: body
          description: 用户登录信息
          required: true
          schema:
            required:
              - username
              - password
            properties:
              username:
                description: 用户账号
                type: string
                example: 'admin'
              password:
                description: 用户密码
                type: string
                example: 1234qwer
      responses:
        '200':
          description: '[SUCCESS]设置成功'
          schema:
            $ref: '#/definitions/ApiResponse'
  /api/add/admin:
    post:
      tags:
        - permission
      summary: 添加代理
      parameters:
        - name: data
          in: body
          description: 代理信息
          required: true
          schema:
            required:
              - groupid
              - aphone
              - apswd
              - atype
              - astatus
              - agold
              - acard
            properties:
              groupid:
                description: 分组id
                type: string
                example: '1'
              aphone:
                description: 用户账号
                type: integer
                example: 1314578585
              apswd:
                description: 用户密码
                type: string
                example: '1qaz2wsx'
              atype:
                description: 代理类型
                type: integer
                example: 1
              astatus:
                description: 用户状态
                type: integer
                example: 1
              agold:
                description: 代理金币数
                type: integer
                example: 10
              acard:
                description: 代理房卡数
                type: integer
                example: 111
      responses:
        '200':
          description: '[SUCCESS]设置成功'
          schema:
            $ref: '#/definitions/ApiResponse'
definitions:
  ApiResponse:
    title: 接口返回对象
    description: 接口返回对象
    properties:
      code:
        description: 状态码
        type: string
        example: SUCCESS
      msg:
        description: 接口返回描述
        type: string
        example: SUCCESS
    type: object
  userInfoResponse:
    title: 用户管理
    description: 用户管理
    properties:
      msg:
        type: string
        example: SUCCESS
      code:
        type: string
        example: SUCCESS
      count:
        type: integer
        example: 50
      data:
        properties:
          uid:
            type: string
            description: 序号
            example: '87'
          uuid:
            type: string
            description: 游戏ID
            example: '87'
          unick:
            type: string
            description: 用户昵称
            example: '闭眼就天黑'
          uphone:
            type: integer
            description: 手机号
            example: 12345678958
          uface:
            description: 头像
            type: string
            example: 1
          uemail:
            description: 邮箱
            type: string
            example: '123548477@qq.com'
          usex:
            description: 性别
            type: string
            example: '男'
          uvip:
            description: vip等级
            type: integer
            example: 1
          u_token:
            description: 游客key
            type: string
            example: 1000
          u_type:
            description: 是否是游客
            type: string
            example: 1000
          status:
            description: 用户状态
            type: string
            example: '正常'
          regist_ip:
            description: 注册地址
            type: string
            example: '145.366.254.45'
          regist_time:
            description: 注册时间
            type: string
            example: '2017-08-12'
          login_ip:
            description: 登录ip
            type: string
            example: '154.36.250.12'
          login_time:
            description: 登录时间
            type: string
            example: '2017-08-23'
          ugold:
            description: 用户金币数量
            type: integer
            example: 1000
          ubank:
            description: 保险柜(银行)金币数量
            type: integer
            example: '11'
          ucard:
            description: 房卡数量
            type: integer
            example: '1'
          roomid:
            description: 当前所在房间
            type: integer
            example: '201708'
        type: object
    type: object
  roomInfoResponse:
    title: 房间信息
    description: 房间信息
    properties:
      msg:
        type: string
        example: SUCCESS
      code:
        type: string
        example: SUCCESS
      count:
        type: integer
        example: 50
      data:
        properties:
          room_id:
            type: integer
            description: 房间ID
            example: '87'
          jushu:
            type: string
            description: 局数
            example: '4局'
          renshu:
            description: 人数
            type: string
            example: '4人'
          play:
            description: 玩法
            type: string
            example: '可下码'
          liudi:
            description: 留底排数
            type: string
            example: '留14张底牌'
          room_type:
            description: 游戏类型(数字)
            type: integer
            example: 11
          room_type_name:
            description: 游戏类型（文字）
            type: string
            example: '麻将游戏'
          room_state:
            description: 房间状态(数字)
            type: integer
            example: 1
          room_state_name:
            description: 房间状态(文字)
            type: string
            example: '正常'
          create_time:
            description: 创建时间
            type: string
            example: '2017-12-02'
          homeowners:
            description: 房主游戏ID
            type: integer
            example: 1
        type: object
    type: object
  regResponse:
    title: 房间信息
    description: 房间信息
    properties:
      msg:
        type: string
        example: SUCCESS
      code:
        type: string
        example: SUCCESS
      count:
        type: integer
        example: 50
      data:
        properties:
          init_gold:
            type: integer
            description: 玩家金币
            example: '87'
          init_bank:
            type: string
            description: 玩家银行资产
            example: '20'
          init_card:
            description: 房卡数量
            type: string
            example: '4'
        type: object
    type: object
  signResponse:
    title: 签到配置列表
    description: 签到配置列表
    properties:
      msg:
        type: string
        example: SUCCESS
      code:
        type: string
        example: SUCCESS
      count:
        type: integer
        example: 50
      data:
        properties:
          glod:
            type: integer
            description: 金币数量
            example: '87'
          card:
            type: string
            description: 房卡数量
            example: '20'
          days:
            description: 连续签到天数
            type: string
            example: '4'
        type: object
    type: object
  EditReg:
    title: 注册配置对象
    description: 注册配置对象
    properties:
      id:
        description: 注册配置表 ID
        type: integer
        example: 3
      init_gold:
        description: 初始化的玩家金币
        type: integer
        example: 1
      init_bank:
        description: 初始化的玩家银行资产
        type: integer
        example: 2
      init_card:
        description: 初始化的玩家房卡数量
        type: integer
        example: 23
    type: object
  signAdd:
    title: 签到配置对象
    description: 签到配置对象
    properties:
      glod:
        description: 奖励的金币数量
        type: integer
        example: 2
      card:
        description: 奖励的房卡数量
        type: integer
        example: 5
      days:
        description: 连续签到天数
        type: integer
        example: 5
    type: object
securityDefinitions:
  api_key:
    type: apiKey
    name: Authorization
    in: header