<?php

namespace App\Bundle\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GameSignRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameSignRepository extends EntityRepository
{
    /**
     * getAll 获取全部数据
     *
     * @author liulian
     *
     * @param  int $page 页码
     * @param int  $size
     *
     * @return \Doctrine\ORM\Query
     */
    public function getAll($page, $size = 20)
    {
        $qb = $this->createQueryBuilder('s');

        return $qb->getQuery()
            ->setFirstResult(($page - 1) * $size)
            ->setMaxResults($size);
    }
}
