<?php

namespace App\Bundle\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GameSignRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameConfigRepository extends EntityRepository
{
}
