<?php

namespace App\Bundle\LoginBundle\Repository;

/**
 * AdminPermissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminPermissionRepository extends \Doctrine\ORM\EntityRepository
{

}
