<?php

namespace App\Bundle\LoginBundle\Repository;

/**
 * AdminMasterPermissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminMasterPermissionRepository extends \Doctrine\ORM\EntityRepository
{
}
